[workspace]
authors = ["canoziia <canoziia@projectk.org>"]
channels = ["conda-forge"]
name = "assignment3"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "python train.py"

[dependencies]
python = ">=3.14.0,<3.15"
pip = ">=25.2,<26"
numpy = ">=2.3.4,<3"
matplotlib = ">=3.10.7,<4"

[pypi-dependencies]
torch = ">=2.9.0, <3"
