[workspace]
authors = ["canoziia <canoziia@projectk.org>"]
channels = ["conda-forge"]
name = "assignment5"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"
